### ISSUE TITLE
Multi-threaded Select operator

### ISSUE THREAD

**Issue by NicholasCorrado** [UWQuickstep/hustle#30]
As the first step towards a multi-threaded implementation of Hustle operators, I will make selections multi-threaded. This will set the stage for multi-threaded implementations of the other operators. I'm seeing if we can reuse any code from the mini-version of Quickstep that UW-Madison submitted for the SIGMOD 2018 contest.

**Comment by pateljm** [comment]
Bravo @NicholasCorrado!
